"""new updates

Revision ID: 9b4e3132652f
Revises: 571f49c3caec
Create Date: 2025-04-03 12:56:13.764969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4e3132652f'
down_revision: Union[str, None] = '571f49c3caec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('from_user_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('to_user_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
